import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "قالب فروشگاهی کارین",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-primary dark:bg-primary-dark dark:text-text-dark"
      >
        {children}
      </body>
    </html>
  );
}
