import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/modules/Header/Header";
import Footer from "./components/modules/footer/Footer";
import Providers from "./providers/Providers";

export const metadata: Metadata = {
  title: "قالب فروشگاهی کارین",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en" className="text-[16px] dark mdl-js" data-scroll-behavior="smooth">
      <body className="font-primary text-[1rem] bg-primary text-text-primary dark:bg-primary-dark dark:text-text-dark">
        <Providers>
          <Header />
          <div>{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
